name: Sync Static Directory

on:
  schedule:
    - cron: '0 * * * *'  # 每小时一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@users.noreply.github.com"
          git remote add upstream https://github.com/vikiboss/60s-static-host.git
          git fetch upstream

      - name: Sync using safe branch method
        run: |
          # 获取当前分支
          CURRENT_BRANCH=$(git branch --show-current)
          echo "Current branch: $CURRENT_BRANCH"
          
          # 创建并切换到临时分支
          git checkout -b sync-temp-branch
          
          # 重置指定目录到上游状态
          git checkout upstream/main -- static
          
          # 检查变化
          if git diff --exit-code --quiet; then
            echo "🟢 No changes detected"
            # 切换回原始分支
            git checkout $CURRENT_BRANCH
          else
            echo "🟠 Changes detected"
            git add static/
            git commit -m "Auto-sync static data [$(date +'%Y-%m-%d %H:%M UTC')]"
            
            # 切换回原始分支并合并
            git checkout $CURRENT_BRANCH
            git merge sync-temp-branch --no-ff -m "Merge static updates"
            git push origin $CURRENT_BRANCH
          fi
          
          # 删除临时分支（确保不在该分支上）
          git branch -D sync-temp-branch
