name: Sync Static Directory

on:
  schedule:
    - cron: '0 * * * *'  # 每小时一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录
          
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@users.noreply.github.com"
          git config pull.rebase false  # 设置合并策略
          
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/vikiboss/60s-static-host.git || true
          git fetch upstream
          
      - name: Create worktree for sync
        run: |
          # 创建临时工作目录
          git worktree add sync-worktree upstream/main
          
      - name: Copy updated static directory
        run: |
          # 清空现有static目录（保留.gitignore等隐藏文件）
          find static -mindepth 1 -delete
          
          # 复制所有文件（包括子目录）
          cp -r sync-worktree/static/* static/
          
          # 列出所有更新文件（调试用）
          echo "Updated files:"
          find static -type f | sed 's/^/  /'
          
      - name: Commit and push changes
        run: |
          # 检查是否有变化
          if git diff --quiet --exit-code; then
            echo "🟢 No changes detected"
          else
            echo "🟠 Changes detected - committing updates"
            
            # 添加所有static目录下的变更
            git add static/
            
            # 提交变更
            git commit -m "Auto-sync static data [$(date +'%Y-%m-%d %H:%M UTC')]"
            
            # 推送变更
            git push origin $(git branch --show-current)
          fi
          
      - name: Cleanup worktree
        run: |
          # 移除工作树
          git worktree remove sync-worktree --force
          
          # 删除工作树目录
          rm -rf sync-worktree
