name: Sync Static Directory

on:
  schedule:
    # 每小时的 0 分运行（每小时一次）
    - cron: '0 * * * *'
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许工作流推送更改

jobs:
  sync-static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/vikiboss/60s-static-host.git
          git fetch upstream

      - name: Sync static directory
        run: |
          # 创建临时分支用于同步
          git checkout -b sync-branch
          
          # 重置到上游 main 分支的 static 目录状态
          git checkout upstream/main -- static
          
          # 检查是否有变化
          if git diff --exit-code; then
            echo "No changes detected"
          else
            # 提交更改
            git add static/
            git commit -m "Auto-sync static directory [$(date +'%Y-%m-%d %H:%M UTC')]"
            
            # 切换到主分支并合并更改
            git checkout main
            git merge sync-branch --no-ff -m "Merge static updates from upstream"
            
            # 推送到仓库
            git push origin main
          fi
          
          # 清理临时分支
          git branch -D sync-branch
